compatibility_date = "2024-08-21"
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiOTc0NzIyYmMtNmMyOC00NDA2LTllZWItMWZhZjQ5NmFhMDI1IiwidGVuYW50X2lkIjoiMjY3ODgxNGYxNDJmMDhlM2ExYmU1YTUyYThiMTI0OWExODAzYjc1MTU2YThhOTY5OWI1ODRhZjExMmIyYmQ4OCIsImludGVybmFsX3NlY3JldCI6ImQ0MWM0NDI0LWUzODQtNGNhYS04YjEwLTQ1ZmVhYjMyYjhmZSJ9.ans3ArOM5SJ_BSYEbI-raSad59YaqLAyjzyhhmumov0"

JWT_SECRET="mysecret"