compatibility_date = "2024-08-21"
[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMjM0OGYxNmEtZGQ2Yi00NWM2LWI0OWUtOTRkYTY3MDkyZWEyIiwidGVuYW50X2lkIjoiMjY3ODgxNGYxNDJmMDhlM2ExYmU1YTUyYThiMTI0OWExODAzYjc1MTU2YThhOTY5OWI1ODRhZjExMmIyYmQ4OCIsImludGVybmFsX3NlY3JldCI6ImQ0MWM0NDI0LWUzODQtNGNhYS04YjEwLTQ1ZmVhYjMyYjhmZSJ9.DmqfTqTRiT6vg89LmIYihtQlmSoOyaBfdkmoCV9kdcs"

JWT_SECRET="mysecret"